android {
    namespace = "com.example.drink_shop"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    defaultConfig {
        // Specify your own unique Application ID
        applicationId = "com.example.drink_shop"
        // Update the following values to match your application needs
        minSdkVersion 21
        targetSdk = flutter.targetSdkVersion
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
    }

    buildTypes {
        release {
            // Add your own signing config for the release build
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}
